Fix stage-qa errors when building a non-default Python flavor when DOCS option is enabled. (e.g. py27 default, try to build py36)
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: %%PYTHON_SITELIBDIR%%/pyaudio.pyc
===> Checking for items in pkg-plist which are not in STAGEDIR
===> Error: Plist issues found.

textproc/py-sphinx is only needed for DOCS here and should be the same flavor as
the port being built to avoid bytecode leftovers.

Do DOCS build in the build stage and simplify DOCS installation

Approved by:	portmgr (blanket)


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@463026 35697150-7ecd-e111-bb59-0022644237b5