Fix obvious typo in upstream code:
  ./libeio/ecb.h:481:3: error: use of undeclared identifier 'retrurn'

This only affects big-endian systems, but still needs to be reported
to the upstream maintainers.

Approved by:	portmgr (tier-2 blankent)


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@510748 35697150-7ecd-e111-bb59-0022644237b5