graphics/gts: Unbreak build WITH=NETPBM
happrox.c:24:10: fatal error: 'pgm.h' file not found

The netpbm update from r451378 moved netpbm headers from include/ to
include/netpbm/, but gts looks for them in include/ only.

While here also clean up the port a little bit:

- Remove NETPBM_DESC since it's already in bsd.options.desc.mk
- Disable netpbm via an autoconf variable instead of patching
  configure

PR:		222958
Reported by:	Phil Pennock <freebsd@phil.spodhuis.org>
Approved by:	erik@bz.bzflag.bz (maintainer timeout, 2 weeks)


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@453643 35697150-7ecd-e111-bb59-0022644237b5