devel/php7{0,1}-intl: switch to C++11, required by ICU >= 59
In file included from /wrkdirs/usr/ports/devel/php70-intl/work/php-7.0.19/ext/intl/intl_convertcpp.cpp:21:
In file included from ./intl_convertcpp.h:26:
/usr/local/include/unicode/unistr.h:3025:7: error: delegating constructors are permitted only in C++11
      UnicodeString(ConstChar16Ptr(text)) {}
      ^~~~~~~~~~~~~
/usr/local/include/unicode/unistr.h:3087:7: error: delegating constructors are permitted only in C++11
      UnicodeString(ConstChar16Ptr(text), length) {}
      ^~~~~~~~~~~~~
/usr/local/include/unicode/unistr.h:3180:7: error: delegating constructors are permitted only in C++11
      UnicodeString(Char16Ptr(buffer), buffLength, buffCapacity) {}
      ^~~~~~~~~~~~~

PR:		218788


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@449614 35697150-7ecd-e111-bb59-0022644237b5