Mark BROKEN: missing header
cc -E -I./h/ - |\
/usr/local/bin/gawk '/^\-\-\-$/ {i=1;next} {if (!i) next} {gsub("\"","");print}' >h/mcompdefs.h
In file included from <stdin>:1:
In file included from ./h/include.h:97:
./h/../h/mp.h:5:10: fatal error: 'gmp.h' file not found

Reported by:	pkg-fallout


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@440896 35697150-7ecd-e111-bb59-0022644237b5