devel/rapidjson: Fix build with Clang 8
include/rapidjson/schema.h:1729:68: error: empty expression statement has no effect; remove unnecessary ';' to silence this warning [-Werror,-Wextra-semi-stmt]
        RAPIDJSON_SCHEMA_HANDLE_PARALLEL_(EndArray, (elementCount));
                                                                   ^

New warnings in Clang => new errors in devel/rapidjson due to the
build having -Werror with -Wall and -Wextra.  This has also happened
during previous Clang version bumps.  Instead of collecting new
-Wno-* every time, disable use of -Werror entirely similar to what
the port already does on tier 2 archs.

PR:		236206
Reported by:	jbeich
Approved by:	portmgr blanket


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@494785 35697150-7ecd-e111-bb59-0022644237b5