Mark BROKEN: fails to package
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: GNUstep/Local/Library/SOGo/AdministrationUI.SOGo/Resources/Hebrew.lproj/Localizable.strings
Error: Orphaned: GNUstep/Local/Library/SOGo/AdministrationUI.SOGo/Resources/Latvian.lproj/Localizable.strings
Error: Orphaned: GNUstep/Local/Library/SOGo/Appointments.SOGo/Resources/Hebrew.lproj/Localizable.strings
Error: Orphaned: GNUstep/Local/Library/SOGo/Appointments.SOGo/Resources/Latvian.lproj/Localizable.strings
Error: Orphaned: GNUstep/Local/Library/SOGo/CommonUI.SOGo/Resources/Hebrew.lproj/Localizable.strings
Error: Orphaned: GNUstep/Local/Library/SOGo/CommonUI.SOGo/Resources/Latvian.lproj/Localizable.strings
Error: Orphaned: GNUstep/Local/Library/SOGo/Contacts.SOGo/Resources/Hebrew.lproj/Localizable.strings
Error: Orphaned: GNUstep/Local/Library/SOGo/Contacts.SOGo/Resources/Latvian.lproj/Localizable.strings
Error: Orphaned: GNUstep/Local/Library/SOGo/ContactsUI.SOGo/Resources/Hebrew.lproj/Localizable.strings
Error: Orphaned: GNUstep/Local/Library/SOGo/ContactsUI.SOGo/Resources/Latvian.lproj/Localizable.strings
Error: Orphaned: GNUstep/Local/Library/SOGo/MailPartViewers.SOGo/Resources/Hebrew.lproj/Localizable.strings
Error: Orphaned: GNUstep/Local/Library/SOGo/MailPartViewers.SOGo/Resources/Latvian.lproj/Localizable.strings
Error: Orphaned: GNUstep/Local/Library/SOGo/Mailer.SOGo/Resources/Hebrew.lproj/Localizable.strings
Error: Orphaned: GNUstep/Local/Library/SOGo/Mailer.SOGo/Resources/Latvian.lproj/Localizable.strings
Error: Orphaned: GNUstep/Local/Library/SOGo/Mailer.SOGo/Resources/SOGoMailHebrewForward.wo/SOGoMailHebrewForward.html
Error: Orphaned: GNUstep/Local/Library/SOGo/Mailer.SOGo/Resources/SOGoMailHebrewForward.wo/SOGoMailHebrewForward.wod
Error: Orphaned: GNUstep/Local/Library/SOGo/Mailer.SOGo/Resources/SOGoMailHebrewReply.wo/SOGoMailHebrewReply.html
Error: Orphaned: GNUstep/Local/Library/SOGo/Mailer.SOGo/Resources/SOGoMailHebrewReply.wo/SOGoMailHebrewReply.wod
Error: Orphaned: GNUstep/Local/Library/SOGo/Mailer.SOGo/Resources/SOGoMailLatvianForward.wo/SOGoMailLatvianForward.html
Error: Orphaned: GNUstep/Local/Library/SOGo/Mailer.SOGo/Resources/SOGoMailLatvianForward.wo/SOGoMailLatvianForward.wod
Error: Orphaned: GNUstep/Local/Library/SOGo/Mailer.SOGo/Resources/SOGoMailLatvianReply.wo/SOGoMailLatvianReply.html
Error: Orphaned: GNUstep/Local/Library/SOGo/Mailer.SOGo/Resources/SOGoMailLatvianReply.wo/SOGoMailLatvianReply.wod
Error: Orphaned: GNUstep/Local/Library/SOGo/MailerUI.SOGo/Resources/Hebrew.lproj/Localizable.strings
Error: Orphaned: GNUstep/Local/Library/SOGo/MailerUI.SOGo/Resources/Latvian.lproj/Localizable.strings
Error: Orphaned: GNUstep/Local/Library/SOGo/MainUI.SOGo/Resources/Hebrew.lproj/Locale
Error: Orphaned: GNUstep/Local/Library/SOGo/MainUI.SOGo/Resources/Hebrew.lproj/Localizable.strings
Error: Orphaned: GNUstep/Local/Library/SOGo/MainUI.SOGo/Resources/Latvian.lproj/Locale
Error: Orphaned: GNUstep/Local/Library/SOGo/MainUI.SOGo/Resources/Latvian.lproj/Localizable.strings
Error: Orphaned: GNUstep/Local/Library/SOGo/PreferencesUI.SOGo/Resources/Hebrew.lproj/Localizable.strings
Error: Orphaned: GNUstep/Local/Library/SOGo/PreferencesUI.SOGo/Resources/Latvian.lproj/Localizable.strings
Error: Orphaned: GNUstep/Local/Library/SOGo/SchedulerUI.SOGo/Resources/Hebrew.lproj/Localizable.strings
Error: Orphaned: GNUstep/Local/Library/SOGo/SchedulerUI.SOGo/Resources/Latvian.lproj/Localizable.strings
Error: Orphaned: GNUstep/Local/Library/SOGo/Templates/SOGoACLHebrewAdditionAdvisory.wox
Error: Orphaned: GNUstep/Local/Library/SOGo/Templates/SOGoACLHebrewModificationAdvisory.wox
Error: Orphaned: GNUstep/Local/Library/SOGo/Templates/SOGoACLHebrewRemovalAdvisory.wox
Error: Orphaned: GNUstep/Local/Library/SOGo/Templates/SOGoFolderHebrewAdditionAdvisory.wox
Error: Orphaned: GNUstep/Local/Library/SOGo/Templates/SOGoFolderHebrewRemovalAdvisory.wox
Error: Orphaned: GNUstep/Local/Library/SOGo/WebServerResources/ckeditor/lang/he.js
Error: Orphaned: GNUstep/Local/Library/SOGo/WebServerResources/ckeditor/lang/lv.js
Error: Orphaned: GNUstep/Local/Library/SOGo/WebServerResources/ckeditor/plugins/scayt/dialogs/dialog.css
Error: Orphaned: GNUstep/Local/Library/SOGo/WebServerResources/ckeditor/plugins/widget/images/handle.png

===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: GNUstep/Local/Library/SOGo/WebServerResources/ckeditor/plugins/clipboard/dialogs/paste.js

Reported by:	pkg-fallout


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@449101 35697150-7ecd-e111-bb59-0022644237b5