lang/rust: Update to 1.23.0
Firefox 57.0 failed to build with Rust 1.23.0 with the following error:

    error: unused import: `std::ascii::AsciiExt`
      --> /wrkdirs/usr/ports/www/firefox/work/firefox-57.0.4/servo/components/style/gecko_string_cache/mod.rs:16:5
       |
    16 | use std::ascii::AsciiExt;
       |     ^^^^^^^^^^^^^^^^^^^^
       |
    note: lint level defined here
      --> /wrkdirs/usr/ports/www/firefox/work/firefox-57.0.4/servo/components/style/lib.rs:26:9
       |
    26 | #![deny(warnings)]
       |         ^^^^^^^^
       = note: #[deny(unused_imports)] implied by #[deny(warnings)]

Now that Firefox is updated to 58.0, the build succeeds.


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@459911 35697150-7ecd-e111-bb59-0022644237b5