devel/py-cffi: Fix build warnings and test failures
CFLAGS contains -Wl,-rpath,${LOCALBASE}/lib, which causes the following
warnings:

warning: -Wl,-rpath,/usr/local/lib: 'linker' input unused

It also causes many tests to fail due to the same warning:

E VerificationError: CompileError: command 'cc' failed with exit status 1

cffi/ffiplatform.py:62: VerificationError
----------- Captured stderr call ----------
error: -Wl,-rpath,/usr/local/lib: 'linker' input unused

Remove these (CFLAGS, LDFLAGS) unnecessary flags as cffi grabs compiler
details from Python and links correctly to libffi/libpython without
them.

* Fix cffi0/test_ownlib to use ${CC} not a hardcoded gcc, unecessarily
  causing test failures. Conditionally add -Wno-shift-negative-value
  to CFLAGS to squash several more failures on FreeBSD 11+ [1]

While I'm here:

* Strip shared library
* Report skipped tests during test runs

Note: leftover test_array_type test failure is known [2]

[1] https://bitbucket.org/cffi/cffi/issues/271
[2] https://bitbucket.org/cffi/cffi/issues/178

Reviewed by:	wg (maintainer)
Approved by:	wg (maintainer)
MFH:		2016Q3
Differential Revision:	D7300


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@419747 35697150-7ecd-e111-bb59-0022644237b5