Explicitly disable C++11 during the build.
Prepare for Qt 5.6, which will pass -std=gnu++11 by default when the compiler
supports it, and the build currently does not work:

../libqtelegram-aseman-edition-6.1-stable/telegram/types/accountdaysttl.cpp:51:10: error: case value evaluates to 3100684255, which cannot be narrowed to type 'int' [-Wc++11-narrowing]
    case typeAccountDaysTTL: {

Note that Qt 5.7 will start requiring C++11 support, so this will need to be
fixed properly in the future.

PR:		211916


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@421293 35697150-7ecd-e111-bb59-0022644237b5