textproc/libxml++26: unbreak build with libc++ 4.0
libxml++/io/istreamparserinputbuffer.cc:42:12: error: no viable conversion from returned value of
      type 'std::istream' (aka 'basic_istream<char>') to function return type 'bool'
    return input_;
           ^~~~~~
libxml++/io/ostreamoutputbuffer.cc:32:12: error: no viable conversion from returned value of type
      'std::ostream' (aka 'basic_ostream<char>') to function return type 'bool'
    return output_;
           ^~~~~~~
libxml++/io/ostreamoutputbuffer.cc:39:12: error: no viable conversion from returned value of type
      'std::ostream' (aka 'basic_ostream<char>') to function return type 'bool'
    return output_;
           ^~~~~~~

PR:		216034
Regressed by:	https://github.com/llvm-mirror/libcxx/commit/3a1b90a866b6
Submitted by:	dim
Approved by:	portmgr blanket


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@431411 35697150-7ecd-e111-bb59-0022644237b5