math/cvc3: unbreak with gcc6 or later
In file included from src/include/expr_manager.h:445:0,
                 from src/include/expr.h:803,
                 from expr.cpp:25:
src/include/expr_value.h: In static member function 'static size_t CVC3::ExprString::hash(const string&)':
src/include/expr_value.h:667:34: error: no match for call to '(std::hash<char*>) (const char*)'
     return s_charHash(str.c_str());
                                  ^
In file included from src/include/hash_map.h:54:0,
                 from src/include/compat_hash_map.h:34,
                 from src/include/expr.h:33,
                 from src/include/assumptions.h:36,
                 from src/include/theorem_producer.h:75,
                 from common_theorem_producer.h:34,
                 from common_theorem_producer.cpp:27:
src/include/hash_table.h: In instantiation of 'Hash::hash_table<_Key, _Value, _HashFcn, _EqualKey, _ExtractKey>::~hash_table() [with _Key = CVC3::Expr; _Value = std::pair<const CVC3::Expr, CVC3::CDOmap<CVC3::Expr, CVC3::Theorem, std::hash<CVC3::Expr> >*>; _HashFcn = std::hash<CVC3::Expr>; _EqualKey = std::equal_to<CVC3::Expr>; _ExtractKey = Hash::_Select1st<std::pair<const CVC3::Expr, CVC3::CDOmap<CVC3::Expr, CVC3::Theorem, std::hash<CVC3::Expr> >*> >]':
src/include/hash_map.h:82:9:   required from 'CVC3::CDMap<Key, Data, HashFcn>::~CDMap() [with Key = CVC3::Expr; Data = CVC3::Theorem; HashFcn = std::hash<CVC3::Expr>]'
common_theorem_producer.h:60:38:   required from here
src/include/hash_table.h:319:5: error: use of deleted function 'std::hash<CVC3::Expr>::~hash()'
     }
     ^


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@433908 35697150-7ecd-e111-bb59-0022644237b5