science/ncnn: fix build with GCC-based architectures
This adds USES=compiler:c11 because of:
/usr/local/poudriere/ports/default/science/ncnn/work/ncnn-20190611-40-gd3be711/src/layer/convolutiondepthwise.cpp:450: error: expected '#pragma omp' clause before 'collapse'

It's detected that our base compiler supports OpenMP and new OpenMP features are then used.

That's why we need new GCC. USES=compiler:openmp would work but it uses a base compiler. Since this port builds also without OpenMP, no further modifications are needed.

Approved by:	mentors (implicit approval)


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@507477 35697150-7ecd-e111-bb59-0022644237b5