Update mono and related ports
USES=mono: minor fixes
 - save a copy of the nuget package in the packages directory
 - force linking of directories, allowing nuget-extract to be rerun
   without `make clean`
 - fix makenuget: nuget requires an equals to identify the version, not a dash

devel/monodevelop: update to 6.2.1.3
 - update nuget packages:
   - link older System.Collection.Immutable 1.1.37 to newer 1.3.1 (used
     by C# and F# respectively)
 - update external github repositories
 - allow post-extract target to be run multiple times
 - change MonoDevelop.Packaging to use a newer version of
   NuGet.Build.Packaging (the older version is no longer fetchable)
 - remove patch integrated upstream
 - moved `nuget restore` patching from post-patch into a patch file (the
   former broke silently)
 - ChangeLog:
   - https://developer.xamarin.com/releases/studio/xamarin.studio_6.2/xamarin.studio_6.2/

irc/smartirc4net: update to 1.1
 - add LICENSE

lang/fsharp: update to 4.1.18
 - add test dependency on libgdiplus
 - update nuget packages
 - update test paths for fsharp assemblies
 - update patches to prevent `nuget restore` from running
 - ChangeLog:
   - Set executable bit correctly on output
   - Integrate visualfsharp
   - Fix regression on binding redirects for System.Collections.Immutable
   - Fix regression in Microsoft.Build.FSharp.targets
   - Fix binding redirects for System.Collections.Immutable
   - Fix version of library going in %PREFIX/lib/mono/fsharp
   - Align fsc task and target file
   - Use install layout that includes mono/fsharp
   - Fix F# Intereactive on Mono 4.9+
   - Update compiler tools
   - Updates to FSharp.Core nuget package for F# 4.1
   - Fix #656: error FS0193: internal error: No access to the given key

lang/mono: various fixes
 - fix linking with lld [1]
 - double maximum handle size [2]
 - add option to run acceptance tests
 - allow for optional bootstrapping of mono via either installed mcs (if
   available) or via downloaded "monolite" (default)
 - add python and py-pillow as dependencies for bin/mono-heapviz
 - add armv6 as a supported architecture (untested)
 - switch to github for source code:
   - official tarball does not include tests
 - patches:
   - recognise FreeBSD for AOT suffix
   - change mono-heapviz to use pillow instead of PIL

multimedia/banshee: tell portscout to ignore this port
 - Portscout was not skipping the 2.9.1 version, and upstream appears to be
   quiet for the last few years.

x11-toolkits/gtk-sharp20: update to 2.12.43
 - ChangeLog:
   - fix compilation on mono-4.8.0 (incorrect use of sizeof())
   - correctly set owned=true on custom constructors

PR:		218885 [1]
PR:		200937 [2]


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@440759 35697150-7ecd-e111-bb59-0022644237b5