net/s3ql: fix build on GCC architectures
Requires C11 compiler:
src/s3ql/deltadump.c:9529: error: passing argument 2 of '__builtin_expect' with different width due to prototype

Approved by:	mentors (implicit approval)


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@507377 35697150-7ecd-e111-bb59-0022644237b5