audio/smasher: unbreak with gcc5 or later (runtime still broken)
In file included from /usr/local/lib/gcc5/include/c++/string:52:0,
                 from /usr/local/include/wx-2.8/wx/string.h:176,
                 from /usr/local/include/wx-2.8/wx/memory.h:16,
                 from /usr/local/include/wx-2.8/wx/object.h:20,
                 from /usr/local/include/wx-2.8/wx/event.h:17,
                 from /usr/local/include/wx-2.8/wx/window.h:19,
                 from /usr/local/include/wx-2.8/wx/control.h:23,
                 from /usr/local/include/wx-2.8/wx/checkbox.h:19,
                 from settingsbook.cpp:4:
/usr/local/lib/gcc5/include/c++/bits/basic_string.h: In instantiation of 'union std::__cxx11::basic_string<wxPoint>::<anonymous>':
/usr/local/lib/gcc5/include/c++/bits/basic_string.h:119:7:   required from 'class std::__cxx11::basic_string<wxPoint>'
fxplotwindow.h:12:32:   required from here
/usr/local/lib/gcc5/include/c++/bits/basic_string.h:121:53: error: member 'wxPoint std::__cxx11::basic_string<wxPoint>::<anonymous union>::_M_local_buf [2]' with constructor not allowed in union
  _CharT           _M_local_buf[_S_local_capacity + 1];
                                                     ^
/usr/local/lib/gcc5/include/c++/bits/basic_string.h:121:53: note: unrestricted unions only available with -std=c++11 or -std=gnu++11

PR:		216707
Reported by:	antoine (via exp-run)


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@433405 35697150-7ecd-e111-bb59-0022644237b5