Fix graphics/ampasACES-container with Clang6.
	aces_formatter.cpp:255:24: error: non-constant-expression cannot
	be narrowed from type 'unsigned int' to 'int32' (aka 'int') in
	initializer list [-Wc++11-narrowing]
		scanLineHeader sh = { yMin + row, scanLineSize };

Reported upstream as well. Not bumping PORTREVISION since this is just
a compile fix.


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@473161 35697150-7ecd-e111-bb59-0022644237b5