databases/mysql55-server: fix build on powerpc64 elfv2
Like other SQL servers, Clang has issues compiling this port:
Wrong types for attribute: inalloca nest noalias nocapture nonnull readnone readonly signext sret zeroext byval dereferenceable(1) dereferenceable_or_null(1)
  %call53 = call signext i32 @my_atomic_cas32(i32* %62, i32* %64, %union.U_32 signext %65)
in function lf_hash_insert
fatal error: error in backend: Broken function found, compilation aborted!

Switch to GCC for now. Since libc++ requires C++11 with GCC, use it instead of C++98.


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@528844 35697150-7ecd-e111-bb59-0022644237b5