Bumped PORTREVISION
Hi

The attached patch fixes the plist of comms/qsstv:

===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: %%PORTDOCS%%%%DOCSDIR%%/images/Gallery_templates.png
Error: Orphaned: %%PORTDOCS%%%%DOCSDIR%%/images/Gallery_txdrm.png
Error: Orphaned: %%PORTDOCS%%%%DOCSDIR%%/manual/Copying.html
Error: Orphaned: %%PORTDOCS%%%%DOCSDIR%%/manual/Gallery_templates.png
Error: Orphaned: %%PORTDOCS%%%%DOCSDIR%%/manual/Gallery_txdrm.png
Error: Orphaned: %%PORTDOCS%%%%DOCSDIR%%/manual/RXDRM.html
Error: Orphaned: %%PORTDOCS%%%%DOCSDIR%%/manual/RXSSTV.html
Error: Orphaned: %%PORTDOCS%%%%DOCSDIR%%/manual/TXDRM.html
Error: Orphaned: %%PORTDOCS%%%%DOCSDIR%%/manual/TXSSTV.html

mfg Tobias

PR:		ports/215124
Submitted by:	@tcberner


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@429190 35697150-7ecd-e111-bb59-0022644237b5