lang/rust: Unbreak on armv6
error: couldn't load codegen backend "/usr/ports/lang/rust/work/rustc-1.37.0-src/build/armv6-unknown-freebsd/stage1/lib/rustlib/armv6-unknown-freebsd/codegen-backends/librustc_codegen_llvm-llvm.so": "/usr/ports/lang/rust/work/rustc-1.37.0-src/build/armv6-unknown-freebsd/stage1/lib/rustlib/armv6-unknown-freebsd/codegen-backends/librustc_codegen_llvm-llvm.so: Undefined symbol \"__clear_cache\""

__clear_cache is implemented in compiler-rt and was dropped upstream with [1]:
https://github.com/rust-lang-nursery/compiler-builtins/commit/aa41e0d25fcb2b11b9b5c269846dd70547f2a787

For some unknown reason this is a problem on armv6.  Bring back the
compiler-rt submodule for now to workaround this.

Submitted by:	 mikael.urankar_gmail.com
Differential Revision:	https://reviews.freebsd.org/D21415


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@510684 35697150-7ecd-e111-bb59-0022644237b5