Fix build of audio/sayonara on 10.4.
	/wrkdirs/usr/ports/audio/sayonara/work/sayonara-player/src/Components/Covers/LocalCoverSearcher.cpp:71:14: error: call to 'abs' is ambiguous
		double d = std::abs(height - width) / (width * 1.0) + 1.0;

While here, remove superfluous patch that now just added a
duplicate #include. Don't bump PORTREVISION because this
only fixes the build on 10.4 and otherwise has no effect
on the package.

Reported by:	pkg-fallout


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@478817 35697150-7ecd-e111-bb59-0022644237b5