games/flukz: Fix build on 12.0-CURRENT
src/soundengine/vorbisdecoder.cpp:352:20: error: cannot initialize return object of type 'unsigned char *' with an rvalue of type 'bool'
            return false;
                   ^~~~~

http://beefy12.nyi.freebsd.org/data/head-amd64-default/p475478_s336801/logs/errors/flukz-0.4.log

- While here add missing dependencies


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@475867 35697150-7ecd-e111-bb59-0022644237b5