Add patch (sent upstream) to drop `using namespace std'
This patch is a smaller version of one I've sent upstream. It removes 'using
namespace std' from Interpreter.cpp to avoid errors when -std=c++11 or
-std=gnu++11 is passed to the compiler, as a call to bind(2) can end up
becoming a call to std::bind().

This is required to avoid breaking the build with Qt 5.6.1:

  c++ -c -O2 -pipe -fstack-protector -fno-strict-aliasing -g -std=gnu++11 -pthread -D_THREAD_SAFE -Wall -W -fPIC -DLINUX -DESPEAK -DSOUND_QMOBILITY -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -I. -I. -I/usr/local/include/espeak -I/usr/local/include/qt5/QtMultimedia -I/usr/local/include/qt5/QtSerialPort -IQtMobility -IQtMobility -I/usr/local/include/qt5 -I/usr/local/include/qt5/QtGui -I/usr/local/include/qt5/QtCore -Itmp/moc -I/usr/local/include -I/usr/local/include -I/usr/local/lib/qt5/mkspecs/freebsd-clang -o tmp/obj/Interpreter.o Interpreter.cpp
  Interpreter.cpp:4282:105: error: invalid operands to binary expression ('__bind<int &, sockaddr *, unsigned long>' and 'int')

PR:		212347
Approved by:	fernando.apesteguia@gmail.com (maintainer)


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@421339 35697150-7ecd-e111-bb59-0022644237b5