games/ultimatestunts: Fix build with Clang 6 and lld
gamerenderer.cpp:81:30: error: non-constant-expression cannot be narrowed from type 'double' to 'GLfloat' (aka 'float') in initializer list [-Wc++11-narrowing]
        GLfloat specular_color[] = {3.0*lightCol.x, 3.0*lightCol.y, 3.0*lightCol.z, 1.0};
                                    ^~~~~~~~~~~~~~

http://beefy12.nyi.freebsd.org/data/head-amd64-default/p475044_s336572/logs/ultimatestunts-0.7.7.1_4.log

- Fix bad absolute symlink
- Mark as LLD_UNSAFE because of audio/openal-soft dependency [1]

PR:	226980 [1]


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@475503 35697150-7ecd-e111-bb59-0022644237b5