Some modules depend on other being there before.
For example, devel_kit needs to be there before a few other, so this
fixes, and allow for future fixes of this kind of problem:

configuring additional dynamic modules
adding module in /wrkdirs/usr/ports/www/nginx-full/work/array-var-nginx-module-0.05
error: ngx_devel_kit is required to build ngx_array_var; please put it before ngx_array_var.

PR:		230864
Submitted by:	mat
exp-runs by:	antoine


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@479404 35697150-7ecd-e111-bb59-0022644237b5