During the exp-run in bug 208158, it was found that deskutils/easystroke gives errors with libc++ 3.8.0:
handler.cc:536:21: error: static declaration of 'abs' follows non-static declaration
static inline float abs(float x) { return x > 0 ? x : -x; }
                    ^
/usr/include/c++/v1/math.h:646:1: note: previous definition is here
abs(float __lcpp_x) _NOEXCEPT {return fabsf(__lcpp_x);}
^

This is because easystroke tries to roll its own version of abs(), which
is already defined in math.h.  Fix this by removing the custom abs().

Approved by:	t@tobik.me (maintainer)
PR:		209372
MFH:		2016Q2


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@414807 35697150-7ecd-e111-bb59-0022644237b5