devel/py-grpcio: fix build on powerpc64 elfv2
Clang doesn't have sys/platform/ppc.h:
cc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -O2 -pipe -fstack-protector-strong -fno-strict-aliasing -O2 -pipe -Ithird_party/boringssl/include -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing -maltivec -mvsx -isystem /usr/local/include -fPIC -DOPENSSL_NO_ASM=1 -D_WIN32_WINNT=1536 -DGPR_BACKWARDS_COMPATIBILITY_MODE=1 -DHAVE_CONFIG_H=1 -DGRPC_ENABLE_FORK_SUPPORT=1 -Isrc/python/grpcio -Iinclude -I. -Ithird_party/abseil-cpp -Ithird_party/address_sorting/include -I/usr/include -Ithird_party/boringssl/include -Ithird_party/upb -Isrc/core/ext/upb-generated -I/usr/include -I/usr/local/include/python3.7m -c third_party/abseil-cpp/absl/base/internal/unscaledcycleclock.cc -o python_build/temp.freebsd-13.0-CURRENT-powerpc-3.7/third_party/abseil-cpp/absl/base/internal/unscaledcycleclock.o -std=c++11 -pthread
third_party/abseil-cpp/absl/base/internal/unscaledcycleclock.cc:24:10: fatal error: 'sys/platform/ppc.h' file not found
#include <sys/platform/ppc.h>
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.

__ppc_get_timebase() and __ppc_get_timebase_freq() are not supported on FreeBSD.

PR:		243995
Approved by:	vanilla (maintainer)


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@525649 35697150-7ecd-e111-bb59-0022644237b5