www/firefox: bump required harfbuzz version
  In file included from gfx/thebes/Unified_cpp_gfx_thebes1.cpp:11:
  gfx/thebes/gfxHarfBuzzShaper.cpp:1571:41: error: use of
    undeclared identifier 'HB_BUFFER_CLUSTER_LEVEL_MONOTONE_CHARACTERS'
    hb_buffer_set_cluster_level(buffer, HB_BUFFER_CLUSTER_LEVEL_MONOTONE_CHARACTERS);
    ^
Reported by:	graemeg on forums.freebsd.org
MFH:		2015Q4


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@404012 35697150-7ecd-e111-bb59-0022644237b5