multimedia/linux_dvbwrapper-kmod: unbreak on 12.0 after r312758
In file included from linux_dvbwrapper.c:43:
/usr/src/sys/sys/capability.h:41:2: error: this file includes <sys/capability.h> which is deprecated [-Werror,-W#warnings]
 #warning this file includes <sys/capability.h> which is deprecated
  ^

Reported by:	pkg-fallout


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@433101 35697150-7ecd-e111-bb59-0022644237b5