astro/wmsolar: Fix build with Clang 6
In file included from wmSolar.c:15:
./wmSolar_mask.xbm:6:12: error: constant expression evaluates to 240 which cannot be narrowed to type 'char' [-Wc++11-narrowing]
 0x00,0x00,0xf0,0xff,0xff,0xff,0xff,0xff,0xff,0x0f,0xf0,0xff,0xff,0xff,0xff,
           ^~~~

http://beefy12.nyi.freebsd.org/data/head-amd64-default/p479076_s338486/logs/errors/wmsolar-1.1.log

In file included from wmSolar.c:18:
./Lunar.h:66:23: error: in-class initializer for static data member of type
      'const double' requires 'constexpr' specifier [-Wstatic-float-init]
  static const double SYNODIC_MONTH = 29.530588861;
                      ^

PR:		230880
Approved by:	tkuiper@inxsoft.net (maintainer timeout, 2 weeks)


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@479272 35697150-7ecd-e111-bb59-0022644237b5